#!/bin/bash

echo "************ Cronny Started ***************"
date >> ${OPENSHIFT_DATA_DIR}/ticktock-start.log

source ${OPENSHIFT_HOMEDIR}/python/virtenv/venv/bin/activate
python ${OPENSHIFT_REPO_DIR}/utils/sync_goodreads_to_resume.py

echo "************ Cronny Executed ***************"
date >> ${OPENSHIFT_DATA_DIR}/ticktock-end.log